import 'package:flutter/material.dart';

Color blackText = const Color(0xff000000);
Color whiteText = const Color(0xffFFFFFF);
Color blackOut = const Color(0xff222222);
Color greenTeal = const Color(0xff0EBE7F);
Color royalIntrigue = const Color(0xff677294);
Color weatheredStone = const Color(0xffC4C4C4);
Color deathVictorious = const Color(0xffC6EFE5);
Color skyline = const Color(0xff959CB4);
Color carbon = const Color(0xff333333);
Color englishManor = const Color(0xff6F7FA1);
Color luxeBlue = const Color(0xff536184);
Color redText = const Color(0xffFF0000);
Color yimnBlue = const Color(0xff2753F3);
Color venetianNights = const Color(0xff765AFC);
Color bloodBurst = const Color(0xffFF484C);
Color livingCoral = const Color(0xffFF6C60);
Color markerGreen = const Color(0xff07D9AD);
Color mangoTango = const Color(0xffFE7F44);
Color fadedSunlight = const Color(0xffFFCF68);
Color skyan = const Color(0xff61CEFF);
